### ISSUE TITLE
Is it possible to manipulate a container/registry specified in a helm chart?

### ISSUE THREAD

**Issue by nerscchris** [Cray-HPE/loftsman#11]
Hi folks,

One thing I've got a query about is if we're sync'ing in 3rd party helm charts in to our system we want to change the images they reference from an external registry to an internal one instead (for a variety of reasons).

Is there a way with loftsman to modify those in some way?  I'm not sure we can manipulate it via the values section.

All the best,
Chris

**Comment by rockholla** [comment]
Hi Chris,

Typically a third-party chart owner would expose the ability to override values for any images that could/should be customizable, in which case you use the loftsman manifest [`values`](https://github.com/Cray-HPE/loftsman/blob/main/schemas/manifests/v1beta1/schema.json#L17) property for a chart to set it to whatever container image you want. 

If that is not exposed via the chart, either the chart owner doesn't intend a container image or images to be anything other than what is hard-coded in the chart, or the owner simply didn't expose the ability by mistake or otherwise. The latter would indeed be a case for using [Helm post-rendering](https://helm.sh/docs/topics/advanced/#post-rendering) which I believe we will make a move to [support via loftsman in some way in the near future](https://github.com/Cray-HPE/loftsman/issues/8). Worth noting you could also simply maintain your own version of the chart as a fork or similar in this case.

I'll go ahead and close this issue for now, but just let me know if you need more help or clarification.

**Comment by nerscchris** [comment]
Hi Patrick,

OK, so the ones I've looked at don't mention the container name in their `values.yaml` presently, though I'm not familiar enough with this to know whether this means they cannot be specified. I'll experiment and see. Thanks!

All the best,
Chris
